/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cat.uvic.teknos.m06.bandhub.app;

import cat.uvic.teknos.m06.bandhub.domain.LinkedList;

import static cat.uvic.teknos.m06.bandhub.utilities.StringUtils.join;
import static cat.uvic.teknos.m06.bandhub.utilities.StringUtils.split;
import static cat.uvic.teknos.m06.bandhub.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
