/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cat.uvic.teknos.m06.bandhub.app;

import java.sql.DriverManager;
import java.sql.SQLException;

public class App {
    public static void main(String[] args) throws SQLException {
        try (var connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/bandhub_test", "root", null)) {
            connection.setAutoCommit(false);
            var preparedStatement = connection.prepareStatement("select id, name from musicalgenre where id = ?");

            preparedStatement.setInt(1, Integer.parseInt(args[0]));

            var resultSet = preparedStatement.executeQuery();
            while (resultSet.next()) {
                System.out.println(
                        "Id: " + resultSet.getInt("id") + ", Name: " +resultSet.getString("name"));
            }

            connection.commit();
        }
    }
}
