/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cat.uvic.teknos.m06.bandhub.app;

import cat.uvic.teknos.m06.bandhub.utilities.SchemaLoader;
import cat.uvic.teknos.m06.bandhub.utilities.SingleLineCommandSchemaLoader;
import cat.uvic.teknos.m06.bandhub.utilities.XmlSchemaLoader;

public class App {
    public static void main(String[] args)  {

        loadSchema(new SingleLineCommandSchemaLoader("dgfhaos", null));
        loadSchema(new XmlSchemaLoader(""));
    }

    private static void loadSchema(SchemaLoader schemaloader) {
       schemaloader.load();
    }
}
